name: Esegui test.py

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_run:
    workflows: ["Nome del workflow precedente"]
    types:
      - completed

jobs:
  
  execute_script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test.py
      run: |
        python test.py
    - name: Commit 
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.csv
        git commit -m 'Add generated CSV files'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     

    - name: push changes
      #uses: ad-m/github-push-action@v0.6.0
      run: |
        git push -f origin master
      env:
      #with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 

        
